version: "3"
services:
  server:
    build: ./hello
    ports:
      - '4000:80'
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '3000:3000'
